import Head from "next/head";
import Footer from "../components/Footer";
import Navbar from "../components/Navbar";
import styles from "../styles/Home.module.css";
import FavMeals from "../components/favMeals";
import Header from "../components/indexHeader";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>FoodRight</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.nav}>
        <Navbar />
      </div>
      <div>
        <Header />
      </div>
      <div>
        <FavMeals />
      </div>
      <div className="row">
        <div className="col-md-12 col-sm-12 col-12">
          <div className="text-center">
            <Footer />
          </div>
        </div>
      </div>
    </div>
  );
}
