import Navbar from "../components/Navbar";
import Head from "next/head";
import React, { useEffect, useState } from "react";
import axios from "axios";
import Image from "next/image";
import Footer from "../components/Footer";
import Home from "./index";
import Modal from "react-modal";
import styles from "../styles/Arrivals.module.css";
import { toast } from "react-toastify";
import ArrivalsCard from "../components/newArrivalsCard";
import SurveryCard from "../components/surveyCard";

export default function NewArrivals() {
  return (
    <>
      <div>
        <Head>
          <title>Arrivals</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="text-center">
          <Navbar />
        </div>
        <div className="row text-center">
          <h1 className="favorite-meals-tag">Arriving Soon!</h1>
        </div>
        <ArrivalsCard />
        <SurveryCard />
      </div>
      <Footer />
    </>
  );
}
